name: Run C++ Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Show files
      run: ls -R

    - name: Compile
      run: g++ TEST/*.cpp -o main

    - name: Run
      run: ./main
